public class checkDatatypes {
    public void MethodBoolean(){
Boolean checkBoolean;
System.debug('Before intialization :' + checkBoolean);
 checkBoolean = true;
System.debug('After intialization :' + checkBoolean);

    }

    public void MethodInteger(){
integer varfirst = 1;
integer varsecond = 2;
System.debug('First variable :' +  varfirst + ' -----'+ 'second variable :' + varsecond);
    }

public void Stringmethod(){
string varname = 'Name:';
string var2name = 'Naciye';
System.debug(varname + ' '+var2name );


}

}
