public class Greetings {
    public String language ='';

  public string GreetHello(){
    string greet = '';
    if(language == 'Hindi'){
        greet = 'Namaste';
    }else if(language=='Turkish'){
        greet ='Merhaba';
    }else if(language=='Russian'){
       greet = 'Pivet';
    }else{
    greet = 'Helloo';
    }
    return greet;
  }
  public string GreetHello2(){
    string greet = ';';

    return greet;
  }
}
