Greetings g1 = new Greetings();
g1.language = 'Hindi';
string g1Greet = g1.GreetHello();
system.debug(g1Greet);

Greetings g2 = new Greetings();
g2.language = 'Turkish';
string g2Greet = g2.GreetHello();
system.debug(g2Greet);

Greetings g3 = new Greetings();
g3.language = 'Pivet';
string g3Greet = g3.GreetHello();
system.debug(g3Greet);

Greetings g4 = new Greetings();
g4.language = 'Heloooo';
string g4Greet = g4.GreetHello();
system.debug(g4Greet);

