ParameterizedMethods.calculate() ;
ParameterizedMethods.calculateWithParam(5, 67);
System.debug(ParameterizedMethods.calculateWithParam(5, 67, 'sum'));
System.debug(ParameterizedMethods.calculateWithParam(100, 67, 'sub'));
System.debug(ParameterizedMethods.calculateWithParam(5, 7, 'multiplication'));
System.debug(ParameterizedMethods.calculateWithParam(30, 6, 'division'));

ParameterizedMethods.calculateEvenOrOdd(5);




