public class GeneralClass {
  public void createStudents(){
    Student S1 = new Student();
    S1.Name ='Naciye';
    S1.Birthdate = date.newInstance(1988, 3, 12);
    S1.SchoolName = 'AIBU';
    system.debug(s1);

    Student S2 = new Student();
    s2.Name ='Ahmet';
    s2.Birthdate = date.newInstance(1987, 11, 15);
    s2.SchoolName = 'AIBU';
    
    system.debug(s2);
  }  

public void justPrintAnything(){
    integer i = 5+5+5+5+9;
    System.debug(i);

}
}
