@istest
public class TurkishLesson5Test {
    // @istest
    // private static void createAccountTest(){
    //     string text = 'Batch8';
    //     TurkishLessonFifth.createAccount(text);
    //     List<account> accList = [select id,name from Account];
    //     system.assertEquals('Batch8', accList[0].name);

    //     List<contact> conList = [select id, FirstName, LastName from Contact];
        
    //     system.assertEquals('Contact 1', conList[0].LastName);
    //     system.assertEquals('Batch8', conList[0].FirstName);
    // }

    
    
}
