public class fullNameClass {
    public void fullNamemethod() {
    string firstName = 'Naciye';
    string lastName = 'Yurul';
    string fullName = firstName + ' ' +lastName;
   
    system.debug(fullName);

    string justName= fullName.remove('Naciye');
    system.debug(justName);
    }
    public void metot1(){
        String myString1 = 'abcd';
        String myString2 = 'ABCD';
        string myString3 = myString1.toUpperCase();
        system.debug(myString3);
    }
}
//string firstname; //declare
//integer num = 10; //declare and tanimlama